---
- hosts: docker
  gather_facts: false
  remote_user: root
  tasks:
    - name: Fetch files from the remote server
      synchronize:
        src: /root/.jenkins/workspace/Myjob_github_ansible_docker/
        dest: /home/aadmin/myproject/projects
        mode: pull
- hosts: ansible
  gather_facts: false
  remote_user: root
  tasks:
  - name: Stopping the container!!!!!
    docker_container:
      name: nginx_container
      image: nginx_image:v1
      state: stopped
  - name: Removing the container 
    docker_container:
      name: nginx_container
      image: nginx_image:v1
      state: absent
  - name: "Its deleting the old inmage!!!"
    docker_image:
      name: nginx_image:v1
      state: absent

  - name: Building the my docker images
    docker_image:
      source: build
      name: nginx_image:v1
      build:
        path: /home/aadmin/myproject/projects/
      state: present
  
  - name: Creating the container and start
    docker_container:
      name: nginx_container
      image: nginx_image:v1
      ports:
        - "8183:80"
      state: started

