---
- hosts: node2
  gather_facts: false
  remote_user: ansible
  tasks:
    - name: Fetch files from jenkins at the remote server
      synchronize:
        src: /var/lib/jenkins/workspace/cicd_ansible_project_1/
        dest: /home/ansible/projects1
        mode: pull
- hosts: node1
  gather_facts: false
  remote_user: ansible
  tasks:
  - name: Stopping the container!!!!!
    docker_container:
      name: nginx_container
      image: nginx_image:v1
      state: stopped
  - name: Removing the container 
    docker_container:
      name: nginx_container
      image: nginx_image:v1
      state: absent
  - name: "Its deleting the old inmage!!!"
    docker_image:
      name: nginx_image:v1
      state: absent

  - name: Building the my docker images
    docker_image:
      source: build
      name: nginx_image:v1
      build:
        path: /home/ansible/projects1/
      state: present
  
  - name: Creating the container and start
    docker_container:
      name: nginx_container
      image: nginx_image:v1
      ports:
        - "8183:80"
      state: started

